#!/bin/bash
for i in src/mvrgx/gui/asset/*.ui; do
    name=$(echo $i | grep '/((?:.(?!/))+)\.ui$' -oP | rg '(\w+)\.ui' -or '$1' --color=never)
    uv run pyside6-uic "${i}" -o "src/mvrgx/gui/ui_${name}.py"
done
